### ISSUE TITLE
[Story] Peer Testing #2 (Term 2 Week 8)

### ISSUE THREAD

**Issue by connordoman** [COSC-499-W2023/year-long-project-team-1#584]
## Description

Features for upcoming peer testing.

### Session 1

||Run Station 1| Participant 1 | Run Station 2 | Participant 2 |
|---|---|---|---|---|
|Team 1|Linh|Seth (Team 3)|Ngan|Mackenzie (Team 18)|
|Team 4|Rahul|Thuan (Team 1)|Lakshay|Kael (Team 5)|
|Team 15|Kyle|Paul (Team 1)|Saksham|Satanshu (Team 10|

### Session 2

||Run Station 1| Participant 1 | Run Station 2 | Participant 2 |
|---|---|---|---|---|
|Team 1|Linh|Beck (Team 5)|Ngan|Mackenzie (Team 18)|
|Team 10|Arsh|Paul (Team 1)|Yafei|Jan (Team 9)|
|Team 18|Sam|Connor (Team 1)|Nikhil|Beth (Team 4)|
|Team 20|Abijith|Abdulhameed (Team 12)|Ryan|Thuan (Team 1)|

### Session 3

||Run Station 1| Participant 1 | Run Station 2 | Participant 2 |
|---|---|---|---|---|
|Team 1|Thuan|Jusnoor (Team 12)|Connor|Zetian (Team 6)|
|Team 6|Jiajun|Linh (Team 1)|Yiqi|Muhammad (Team 9)|
|Team 10|Arsh|Ngan (Team 1)|Ahmed|Saksham (Team 15)|

### Session 4

||Run Station 1| Participant 1 | Run Station 2 | Participant 2 |
|---|---|---|---|---|
|Team 1|Thuan|Sam (Team 18)|Paul|Issa (Team 20)|
|Team 4|Beth|Connor (Team 1)|Denis|Muhammad (Team 9)|
|Team 5|Kael|Ngan (Team 1)|Abhinav|Zeitain (Team 6)|

## Todo

- [x] User selectable blurring regions
    - [x] Add to censorship UI
    - [x] Add to video processing logic
- [x] Clients will be prompted to register before viewing appointment if not yet registered (**Cognito registration**)
    - [x] #635
    - [x] API route for registration
- [x] ~Professionals identity management integrated into service~
    - [x] ~Designated professionals can edit others~
    - [x] ~Edit UI~
    - [x] ~List UI~
    - [x] ~API route to edit~
    - [x] ~API route to list~
    - [x] ~API route to create~
    - [x] ~API route to delete~
- [x] Templated feedback from professionals to clients
- [ ] Clients can download censored videos
    - [x] API route to request resource URI

Not in original spec:

- [x] #585
  - [x] Fetch all appointments, metadata
- [x] Conversation/Appointment viewer (timeline of single appointment)
  - [x] Descending timeline of appointments (newest first)
  - Similar to the following: ![appointment list (CLIENT after vid upload)](https://github.com/COSC-499-W2023/year-long-project-team-1/assets/3927471/6315d859-491c-4e79-b936-fd434347ddde)

We have decided to move focus away from Professional identity management since it is not a core feature of our app i.e. it does not fit our app's core mission.

## Notes

- Templated feedback: this would essentially require an implementation of chat messages.
  - Add an additional table in DB: `Message(apptId, sender: User, timestamp)`
  - Appointment page does one fetch
    - API merges list of Videos with Messages by timestamp (chronological order)
    - API returns this list of "events"
    - Page iterates events, displays either message or video upload
